GET http://localhost:3030/customers

####

Post http://localhost:3030/customers HTTP/1.1
content-Type: application/json

{  

    "patientFirstName": "chiara",
    "patientLastName": "suffredini",
    "patientDateOfBirth": "Wed, 21 Oct 2015 18:27:50 GMT",
    "patientPhoneNumber": "3475696873",
    "patientAddress": "via romana 10, lucca",
    "patientEmail":"maria@gmail.com",
    "patientTreatments": "igiene dentale"
    
}

####

DELETE http://localhost:3030/customers/63b73078e1c29cc76f5a605b HTTP/1.1

####

POST http://localhost:3030/assistedByDoctor/63b73074e1c29cc76f5a6059 HTTP/1.1
content-Type: application/json

{  
        "doctorName":"faty",
        "doctorLastName":"elba",
        "doctorId":"639b7c7fca871675b3d3b3ca"
    
}
