GET http://localhost:3030/customers

####

Post http://localhost:3030/newCustomers HTTP/1.1
content-Type: application/json

{  

    "patientFirstName": "Giovanni",
    "patientLastName": "Dilorenzo",
    "patientDateOfBirth": "Wed, 30 Oct 2015 18:27:50 GMT",
    "patientPhoneNumber": "33456786",
    "patientAddress": "via di piano 7, lucca",
    "patientEmail":"giovanniDilo@gmail.com",
    "patientTreatments": "igiene dentale",
    "patientAvatar": "https://i.pinimg.com/564x/63/f5/31/63f531e84f6a30df939f06edef46ead1.jpg"
    
}

####

DELETE http://localhost:3030/customers/63fb4b49ed2322b1106d0697 HTTP/1.1

####
PATCH http://localhost:3030/customers/63fe28b4bf30176c7f1636a0 HTTP/1.1
content-type: application/json

{
    "patientTreatments": "igiene dentale",
   "patientAvatar": "https://i.pinimg.com/564x/22/ab/bf/22abbf8a4dde67a4bf1f9e7303279198.jpg"
}

####

POST http://localhost:3030/assistedByDoctor/63fe2cb89ce2c8bbcad9a5c9 HTTP/1.1
content-Type: application/json

{  
        "doctorName":"wisal",
        "doctorLastName":"elbasraoui",
        "doctorId":"63f23b5cdabdeab2ac4000a6"
    
}


