GET http://localhost:3030/customers

####

Post http://localhost:3030/customers HTTP/1.1
content-Type: application/json

{  

    "patientFirstName": "diego",
    "patientLastName": "suffre",
    "patientDateOfBirth": "Wed, 24 Oct 2015 18:27:50 GMT",
    "patientPhoneNumber": "3rtyui3",
    "patientAddress": "vias.annunziata, ddfrtgyhlucca",
    "patientEmail":"gtbfhyju@gmail.com",
    "patientTreatments": "igiene dentale"
    
}

####

DELETE http://localhost:3030/customers/63b73078e1c29cc76f5a605b HTTP/1.1

####

POST http://localhost:3030/assistedByDoctor/63e53deefc4ab34cc6f6ba8c HTTP/1.1
content-Type: application/json

{  
        "doctorName":"sofy",
        "doctorLastName":"elbass",
        "doctorId":"63c9765cfc68ba850db6a10b"
    
}
